spring.datasource.url= mysql --host=us-cdbr-iron-east-02.cleardb.net --user=b5bb05db5a45d2 --password=377efeaa --reconnect heroku_f6a3ada2993cc51

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false